import { useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { FaDownload, FaCopy, FaShare, FaPrint, FaFilePdf, FaFileExcel } from 'react-icons/fa';


const Export = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const [titles, setTitles] = useState([]);
  const [exportFormat, setExportFormat] = useState('txt');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (location.state?.titles) {
      setTitles(location.state.titles);
    } else {
      navigate('/');
    }
  }, [location.state, navigate]);

  const exportFormats = [
    { id: 'txt', name: 'Text File (.txt)', icon: <FaDownload /> },
    { id: 'csv', name: 'Excel CSV (.csv)', icon: <FaFileExcel /> },
    { id: 'pdf', name: 'PDF Document (.pdf)', icon: <FaFilePdf /> },
    { id: 'json', name: 'JSON Data (.json)', icon: <FaDownload /> }
  ];

  const handleCopyAll = () => {
    const allTitles = titles.join('\n');
    navigator.clipboard.writeText(allTitles);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My Generated Titles from TitleBolt',
          text: titles.join('\n'),
          url: window.location.origin
        });
      } catch (err) {
        console.log('Error sharing:', err);
      }
    } else {
      handleCopyAll();
    }
  };

  const handleDownload = () => {
    let content = '';
    let filename = '';
    let mimeType = '';

    switch (exportFormat) {
      case 'txt':
        content = titles.join('\n');
        filename = 'titlebolt-titles.txt';
        mimeType = 'text/plain';
        break;
      case 'csv':
        content = 'Title,Length,Words\n' + titles.map(title => 
          `"${title}",${title.length},${title.split(' ').length}`
        ).join('\n');
        filename = 'titlebolt-titles.csv';
        mimeType = 'text/csv';
        break;
      case 'json':
        content = JSON.stringify({
          titles: titles.map((title, index) => ({
            id: index + 1,
            title,
            length: title.length,
            words: title.split(' ').length,
            generated: new Date().toISOString()
          })),
          exported: new Date().toISOString(),
          source: 'TitleBolt AI Generator'
        }, null, 2);
        filename = 'titlebolt-titles.json';
        mimeType = 'application/json';
        break;
      case 'pdf':
        // For PDF, we'll simulate the download
        alert('PDF export feature coming soon! Use Text format for now.');
        return;
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>TitleBolt - Generated Titles</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { color: #6366f1; }
            .title { padding: 10px; margin: 5px 0; border: 1px solid #ddd; }
            .footer { margin-top: 30px; font-size: 12px; color: #666; }
          </style>
        </head>
        <body>
          <h1>TitleBolt - AI Generated Titles</h1>
          <p>Generated on: ${new Date().toLocaleDateString()}</p>
          ${titles.map((title, index) => 
            `<div class="title">${index + 1}. ${title}</div>`
          ).join('')}
          <div class="footer">
            Generated by TitleBolt AI - Visit titlebolt.online for more titles
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  if (!titles.length) {
    return (
      <div className="container" style={{ padding: '40px 20px', textAlign: 'center' }}>
        <h2>No titles to export</h2>
        <button onClick={() => navigate('/')} className="btn-primary">
          Generate New Titles
        </button>
      </div>
    );
  }

  return (
    <div className="container" style={{ padding: '40px 20px' }}>

      
      <div style={{ textAlign: 'center', marginBottom: '40px' }}>
        <h1 style={{ fontSize: '2.5rem', marginBottom: '16px' }}>
          📥 Export & Save Your Titles
        </h1>
        <p style={{ fontSize: '1.2rem', color: 'var(--text-secondary)' }}>
          Download, share, or save your AI-generated titles in multiple formats
        </p>
      </div>

      {/* Export Stats */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '20px',
        marginBottom: '40px'
      }}>
        <div style={{
          padding: '20px',
          background: 'var(--bg-card)',
          border: '1px solid var(--border)',
          borderRadius: '12px',
          textAlign: 'center'
        }}>
          <div style={{ fontSize: '2rem', fontWeight: '700', color: 'var(--primary)' }}>
            {titles.length}
          </div>
          <div style={{ color: 'var(--text-secondary)' }}>Total Titles</div>
        </div>
        <div style={{
          padding: '20px',
          background: 'var(--bg-card)',
          border: '1px solid var(--border)',
          borderRadius: '12px',
          textAlign: 'center'
        }}>
          <div style={{ fontSize: '2rem', fontWeight: '700', color: 'var(--success)' }}>
            {Math.round(titles.reduce((acc, title) => acc + title.length, 0) / titles.length)}
          </div>
          <div style={{ color: 'var(--text-secondary)' }}>Avg. Length</div>
        </div>
        <div style={{
          padding: '20px',
          background: 'var(--bg-card)',
          border: '1px solid var(--border)',
          borderRadius: '12px',
          textAlign: 'center'
        }}>
          <div style={{ fontSize: '2rem', fontWeight: '700', color: 'var(--secondary)' }}>
            {Math.round(titles.reduce((acc, title) => acc + title.split(' ').length, 0) / titles.length)}
          </div>
          <div style={{ color: 'var(--text-secondary)' }}>Avg. Words</div>
        </div>
      </div>



      {/* Export Format Selection */}
      <div style={{ marginBottom: '40px' }}>
        <h3 style={{ marginBottom: '20px', fontSize: '1.8rem' }}>
          📄 Choose Export Format
        </h3>
        <div style={{ 
          display: 'grid', 
          gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', 
          gap: '16px' 
        }}>
          {exportFormats.map((format) => (
            <div
              key={format.id}
              onClick={() => setExportFormat(format.id)}
              style={{
                padding: '16px',
                background: exportFormat === format.id ? 'var(--primary)' : 'var(--bg-card)',
                color: exportFormat === format.id ? 'white' : 'var(--text-primary)',
                border: '2px solid',
                borderColor: exportFormat === format.id ? 'var(--primary)' : 'var(--border)',
                borderRadius: '12px',
                cursor: 'pointer',
                transition: 'all 0.2s',
                display: 'flex',
                alignItems: 'center',
                gap: '12px'
              }}
            >
              <div style={{ fontSize: '1.2rem' }}>
                {format.icon}
              </div>
              <div>{format.name}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Quick Actions */}
      <div style={{ marginBottom: '40px' }}>
        <h3 style={{ marginBottom: '20px', fontSize: '1.8rem' }}>
          ⚡ Quick Actions
        </h3>
        <div style={{ 
          display: 'grid', 
          gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', 
          gap: '16px' 
        }}>
          <button 
            onClick={handleCopyAll}
            style={{
              padding: '16px',
              background: copied ? 'var(--success)' : 'var(--bg-card)',
              color: copied ? 'white' : 'var(--text-primary)',
              border: '2px solid',
              borderColor: copied ? 'var(--success)' : 'var(--border)',
              borderRadius: '12px',
              fontSize: '14px',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '8px',
              transition: 'all 0.2s'
            }}
          >
            <FaCopy /> {copied ? 'Copied!' : 'Copy All'}
          </button>

          <button 
            onClick={handleShare}
            style={{
              padding: '16px',
              background: 'var(--bg-card)',
              color: 'var(--text-primary)',
              border: '2px solid var(--border)',
              borderRadius: '12px',
              fontSize: '14px',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '8px',
              transition: 'all 0.2s'
            }}
            onMouseOver={(e) => e.target.style.transform = 'translateY(-2px)'}
            onMouseOut={(e) => e.target.style.transform = 'translateY(0)'}
          >
            <FaShare /> Share
          </button>

          <button 
            onClick={handlePrint}
            style={{
              padding: '16px',
              background: 'var(--bg-card)',
              color: 'var(--text-primary)',
              border: '2px solid var(--border)',
              borderRadius: '12px',
              fontSize: '14px',
              fontWeight: '600',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: '8px',
              transition: 'all 0.2s'
            }}
            onMouseOver={(e) => e.target.style.transform = 'translateY(-2px)'}
            onMouseOut={(e) => e.target.style.transform = 'translateY(0)'}
          >
            <FaPrint /> Print
          </button>
        </div>
      </div>

      {/* Title Preview */}
      <div style={{ marginBottom: '40px' }}>
        <h3 style={{ marginBottom: '20px', fontSize: '1.8rem' }}>
          👀 Preview Your Titles
        </h3>
        <div style={{
          maxHeight: '300px',
          overflowY: 'auto',
          padding: '20px',
          background: 'var(--bg-card)',
          border: '1px solid var(--border)',
          borderRadius: '12px'
        }}>
          {titles.map((title, index) => (
            <div
              key={index}
              style={{
                padding: '12px 0',
                borderBottom: index < titles.length - 1 ? '1px solid var(--border)' : 'none',
                display: 'flex',
                alignItems: 'flex-start',
                gap: '12px'
              }}
            >
              <span style={{
                minWidth: '24px',
                height: '24px',
                background: 'var(--primary)',
                color: 'white',
                borderRadius: '50%',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '12px',
                fontWeight: '600'
              }}>
                {index + 1}
              </span>
              <span style={{ flex: 1 }}>{title}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Download Button */}
      <div style={{ textAlign: 'center', marginBottom: '40px' }}>
        <button 
          onClick={handleDownload}
          style={{
            padding: '20px 40px',
            background: 'linear-gradient(135deg, var(--primary), var(--secondary))',
            color: 'white',
            border: 'none',
            borderRadius: '12px',
            fontSize: '18px',
            fontWeight: '700',
            cursor: 'pointer',
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: '12px',
            transition: 'transform 0.2s',
            boxShadow: '0 4px 12px rgba(99, 102, 241, 0.3)'
          }}
          onMouseOver={(e) => e.target.style.transform = 'translateY(-3px)'}
          onMouseOut={(e) => e.target.style.transform = 'translateY(0)'}
        >
          <FaDownload /> Download {exportFormats.find(f => f.id === exportFormat)?.name}
        </button>
      </div>

      {/* Navigation */}
      <div style={{ 
        display: 'grid', 
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', 
        gap: '16px',
        marginBottom: '40px'
      }}>
        <button 
          onClick={() => navigate('/results', { state: { titles } })}
          style={{
            padding: '12px 20px',
            background: 'var(--bg-card)',
            color: 'var(--text-primary)',
            border: '2px solid var(--border)',
            borderRadius: '8px',
            fontSize: '14px',
            fontWeight: '600',
            cursor: 'pointer',
            transition: 'transform 0.2s'
          }}
          onMouseOver={(e) => e.target.style.transform = 'translateY(-2px)'}
          onMouseOut={(e) => e.target.style.transform = 'translateY(0)'}
        >
          Back to Results
        </button>

        <button 
          onClick={() => navigate('/')}
          style={{
            padding: '12px 20px',
            background: 'var(--primary)',
            color: 'white',
            border: 'none',
            borderRadius: '8px',
            fontSize: '14px',
            fontWeight: '600',
            cursor: 'pointer',
            transition: 'transform 0.2s'
          }}
          onMouseOver={(e) => e.target.style.transform = 'translateY(-2px)'}
          onMouseOut={(e) => e.target.style.transform = 'translateY(0)'}
        >
          Generate New Titles
        </button>
      </div>


    </div>
  );
};

export default Export;